sample number: 96169
output_dim: 8
token_size: 7057
ans_type_to_idx: {'yes/no': 0, 'action': 1, 'object': 2, 'location': 3, 'other': 4, 'color': 5, 'human': 6, 'number': 7}
sample number: 18473
output_dim: 8
token_size: 7057
ans_type_to_idx: {'yes/no': 0, 'action': 1, 'object': 2, 'location': 3, 'other': 4, 'color': 5, 'human': 6, 'number': 7}
[[ 0.48409   0.33505   0.42066  ... -1.7047   -0.62474   0.69989 ]
 [ 0.14354   0.057574  0.070036 ... -0.057567 -0.037463  0.060437]
 [-7.1395   -2.4339   -2.5181   ... -4.8147   -5.1779    6.7697  ]
 ...
 [ 3.9665   -0.4368   -4.9797   ...  1.2008   -2.9568    2.8831  ]
 [-1.0742    0.28313  -1.0317   ...  2.0254   -1.347     0.38743 ]
 [ 1.2023   -1.0608   -0.7661   ...  2.0222    2.6343    3.7644  ]]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb1d80d5e50>
Traceback (most recent call last):
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1481, in __del__
    self._shutdown_workers()
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1445, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ndhuynh/.conda/envs/cartoon/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 71, in _wrap
    pass  # SIGINT; Killed by parent, do nothing
KeyboardInterrupt